# Generated by Django 6.0.5 on 2026-06-06 16:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0002_clubcategory_alter_club_options_club_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='club',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
