# Generated by Django 6.0.5 on 2026-06-06 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0003_alter_club_created_at_alter_club_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club',
            name='category',
        ),
        migrations.DeleteModel(
            name='ClubCategory',
        ),
    ]
